---
ID: "bf61e80e-1e37-40b4-9527-f717d2c6877c"
Parent: "79ec1bec-eb20-4dd4-9fd7-4fadf896b89e"
Template: "79ec1bec-eb20-4dd4-9fd7-4fadf896b89e"
Path: /sitecore/templates/Feature/Common/Page Content/Image/Image Parameters/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: sxa/16x16/promo.png
- ID: "19b597d3-2edd-4ae2-aefe-4a94c7f10e31"
  Hint: __Source Item
  Value: "sitecore://master/{B5F7104D-9EAC-401A-8F21-909402F9E4C3}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c77bc424-d2d2-469f-bbfb-85ef272a1eb8"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b86697d-60ca-4d80-83fb-7555a2e6ce1c"
      Hint: __Source
      Value: "sitecore://master/{B5F7104D-9EAC-401A-8F21-909402F9E4C3}?lang=en&ver=1"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241107T185607Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eae8a19a-6fd0-45f7-9deb-b4af443fc656"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jflheureux@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250513T211112Z
