---
ID: "8bca9113-b147-44b8-8d47-e4c0c0d8b59b"
Parent: "0f593039-9211-41e5-b469-3648bc93b5fb"
Template: "bc9bb684-36df-4285-888b-d8b4d87b10de"
Path: /sitecore/system/Settings/Feature/JSS Experience Accelerator/Tidal Site/Tidal Site Setup/Replace Tidal Placeholder Settings
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "c0a5bd91-e658-46ce-b631-77ce337d8e6e"
  Hint: Script
  Value: "{831255F8-5EB4-4740-B7BE-162B160A1190}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c4b7c058-17f3-4507-a2a6-7d68557c86e4"
Languages:
- Language: "de-DE"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d84fd831-bad7-4626-8647-8fa2d5f312f0"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Home Renderings hinzufügen
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250814T223012Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cf1a9eb-9739-44c9-b627-7d119c36aa4b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250814T223012Z
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220609T115421Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e10cb507-71f8-462b-a29d-19a9430b42d9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jmurphy@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250818T194626Z
- Language: "ja-JP"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d84fd831-bad7-4626-8647-8fa2d5f312f0"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: ホームレンダリングを追加
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250814T223012Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cf1a9eb-9739-44c9-b627-7d119c36aa4b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250814T223012Z
- Language: "zh-CN"
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d84fd831-bad7-4626-8647-8fa2d5f312f0"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 添加主页渲染
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250814T223012Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cf1a9eb-9739-44c9-b627-7d119c36aa4b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250814T223012Z
