---
ID: "17f97288-e4bd-4a52-be89-37b473a8c4d2"
Parent: "438177fb-b8aa-4abb-8d4f-c5766c16cda5"
Template: "438177fb-b8aa-4abb-8d4f-c5766c16cda5"
Path: /sitecore/templates/Feature/Common/Events/EventCard/EventCard/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "383e60e6-9e1a-44ed-9074-d55198459cd3"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "06fe7e7f-2451-47c0-b0cf-dc6bfeca6744"
      Hint: image
      Value: |
        <image mediaid="{FB70BF8B-1254-4326-8FB7-C136E49E68C8}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T212249Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "47206f9e-b331-43a1-bbd2-f2471158f2da"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Event Card Heading
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124930Z
