// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 16:04:18 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { ArticleCard, theme } from '@sitecore-search/ui';

const PersonRootStyled = styled(ArticleCard.Root)`
  box-sizing: border-box;
  position: relative;
  width: 100%;
  min-height: 0;
  max-width: 100%;
  display: flex;
`;

const PersonImageWrapper = styled.div`
  aspect-ratio: 1/1;
`;

const PersonImageStyled = styled(ArticleCard.Image)`
  object-fit: cover;
  object-position: center;
  width: 100%;
  height: 100%;
`;

const PersonContentStyled = styled(ArticleCard.Content)`
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: ${theme.vars.typography.fontSize3.fontSize};
  display: flex;
  flex-direction: column;
  flex: 1;
`;

const PersonTitleStyled = styled(ArticleCard.Title)``;

const PersonLinkStyled = styled.a`
  text-decoration: none;
  color: ${theme.vars.palette.text.primary};
  font-size: ${theme.vars.typography.fontSize4.fontSize};
  &:hover {
    text-decoration: underline;
  }
  &:focus {
    text-decoration: underline;
    outline-color: ${theme.vars.palette.grey['800']};
  }
`;

const PersonSpan = styled.span`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
`;

const PersonSubtitle = styled(ArticleCard.Subtitle)`
  color: ${theme.vars.palette.text.primary};
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  font-weight: ${theme.vars.typography.fontSize3.fontWeight};
  line-height: ${theme.vars.typography.fontSize2.lineHeight};
  bottom: ${theme.vars.spacing.s};
`;

const PersonContentTextStyled = styled.div`
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  font-size: ${theme.vars.typography.fontSize1.fontSize};
  line-height: ${theme.vars.typography.fontSize1.lineHeight};
  margin-bottom: ${theme.vars.spacing.m};
`;

export const PersonItemCardStyled = {
  Link: PersonLinkStyled,
  Content: PersonContentStyled,
  ImageWrapper: PersonImageWrapper,
  Image: PersonImageStyled,
  Title: PersonTitleStyled,
  Root: PersonRootStyled,
  Span: PersonSpan,
  Text: PersonContentTextStyled,
  Subtitle: PersonSubtitle,
};
