// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { useCallback, useMemo, useRef, useEffect, useState, startTransition } from 'react';
import React from 'react';
import { createRoot } from 'react-dom/client';
import Head from 'next/head';
import Script from 'next/script';
import Frame from 'component-children/Shared/Frame/Frame';
import { ContainedWrapper } from 'component-children/Shared/Containers/ContainedWrapper';
import { Text, RichText, withDatasourceCheck, useSitecore, Placeholder, NextImage, Image, Link as Link_8a80e63291fea86e0744df19113dc44bec187216, CdpHelper } from '@sitecore-content-sdk/nextjs';
import { useTranslation } from 'lib/hooks/useTranslation';
import { useFrame, FrameProvider } from 'lib/hooks/useFrame';
import { getGraphQlClient } from 'lib/graphql-client';
import { BUSINESS_PROFILE_TEMPLATE_ID, NEWS_TEMPLATE_ID, INSIGHTS_TEMPLATE_ID, LANDING_PAGE_TEMPLATE_ID, HEADER_CHILD_ID, HEADER_LINK_GROUP_ID, HEADER_LINK_ID, FOOTER_SOCIAL_LINK_TEMPLATE_ID, FOOTER_LINK_TEMPLATE_ID, ARTICLE_TEMPLATE_ID } from 'lib/graphql/id';
import { PRIMARY_THEME, TERTIARY_THEME, SECONDARY_THEME } from 'lib/const';
import { getLayoutLanguage, getSiteName, fetchSiteRootInfo, contentRootIdNullChecker, extractHashParams, mergeHashParams, placeholderGenerator, cn as cn_ad38580a4d9ab18fff637eb37486c819409ee6c0, pageEditCheck, getPeoplePageDisplayName, downloadICS, normalizeSxaTags } from 'lib/helpers';
import { GetBusinessProfiles, GetProductDocuments, GetTertiaryNavigation, GetItemById, GetSideNavigation, GetHeaderNavigation, GetContentTreeNavigation, GetFooterLegalSocialLinks, GetFooterColumnLinks, GetLatestArticles, GetLatestInsights, GetLatestNews } from 'graphql/generated/graphql-documents';
import { StoreListItem } from 'component-children/WhereToBuy/StoreListItem';
import { LoadMoreButton } from 'component-children/WhereToBuy/LoadMoreButton';
import { TabsContainer } from 'component-children/Tabs/TabsContainer/TabsContainer';
import { TAB_LAYOUTS } from 'lib/helpers/tabs';
import { TabItem } from 'component-children/Tabs/TabItem/TabItem';
import { WidgetsProvider } from '@sitecore-search/react';
import SimplePageListingWithFiltersWidget from 'src/widgets/SearchResults/SimplePageListingWithFiltersResults';
import { SEARCH_CONFIG } from 'lib/const/search-const';
import { NoWidgetIdError } from 'src/components/Search/NoWidgetIdError';
import { useRouter } from 'next/router';
import GlobalSearchComponentWidget from 'src/widgets/SearchResults/GlobalSearch/index';
import ProductSearchWidget from 'src/widgets/SearchResults/ProductSearch/index';
import PeopleSearchComponentWidget from 'src/widgets/SearchResults/PeopleSearch';
import SearchListingWithFiltersWidget from 'src/widgets/SearchResults/SearchListingWithFiltersResults';
import { ARTICLE_VARIANTS } from 'lib/helpers/article-variants';
import KnowledgeCenterSearchWidget from 'src/widgets/SearchResults/KnowledgeCenterSearch';
import EventListingWithFiltersWidget from 'src/widgets/SearchResults/EventListingWithFiltersResults';
import ArticleListingWithFiltersWidget from 'src/widgets/SearchResults/ArticleListingWithFiltersResults';
import { ProductTechSpecs } from 'component-children/Product/ProductTechSpecs/ProductTechSpecs';
import { ProductResources } from 'component-children/Product/ProductResources/ProductResources';
import { ProductOverview } from 'component-children/Product/ProductOverview/ProductOverview';
import { ProductOrderingInfo } from 'component-children/Product/ProductOrderingInfo/ProductOrderingInfo';
import ProductHeader from 'component-children/Product/ProductHeader/ProductHeader';
import ProductMetaData from 'component-children/Product/ProductHeader/ProductMetaData';
import { ProductDocuments } from 'component-children/Product/ProductDocuments/ProductDocuments';
import PersonProfileRendering from 'component-children/People/PersonProfile/PersonProfile';
import SimplePageListingRendering from 'component-children/Page Content/SimplePageListing/SimplePageListing';
import { getPageListingWithDetails } from 'lib/helpers/listing/page-listing';
import { cn } from 'lib/helpers/classname';
import { FullWidthWrapper } from 'component-children/Shared/Containers/FullWidthWrapper';
import { useImage } from 'lib/hooks/useImage';
import { Wrapper } from 'component-children/Shared/Containers/Wrapper';
import CTABlock from 'component-children/Page Content/CTABlock/CTABlock';
import { ContentBlockImageLeft } from 'component-children/Page Content/ContentBlock/ContentBlockImageLeft';
import ContentBlock from 'component-children/Page Content/ContentBlock/ContentBlock';
import { Button } from 'component-children/Shared/Button/Button';
import Button_e5ef0f25383a4b5a7bc1027fc8ac4045058cb2fe from 'component-children/Shared/Button/Button';
import { fetchAlertBannerData, AlertBanner, AlertBannerEditRendering } from 'component-children/Page Content/AlertBanner/AlertBanner';
import { mainLanguage, availableLanguages } from 'lib/i18n/i18n-config';
import { AccordionProvider, useAccordion } from 'lib/hooks/useAccordion';
import { AccordionMotion } from 'component-children/Shared/Animation/AccordionMotion';
import ButtonIcon from 'component-children/Shared/Button/ButtonIcon';
import { PersonaSwitcher } from 'component-children/Navigation/PersonaSwitcher/PersonaSwitcher';
import { Login } from 'component-children/Navigation/Login/Login';
import { isAuthEnabled } from 'lib/helpers/auth';
import { fetchAuthConfig } from 'lib/helpers/site-config-helpers';
import { LanguageSwitcher } from 'component-children/Navigation/LanguageSwitcher/LanguageSwitcher';
import Link from 'next/link';
import { PageList } from 'component-children/Navigation/Header/PageList';
import { usePathname } from 'next/navigation';
import { SearchModal } from 'component-children/Search/SearchModal';
import { getPagePathList } from 'component-children/Navigation/Breadcrumbs/Breadcrumbs';
import BreadcrumbsRendering from 'component-children/Navigation/Breadcrumbs/Breadcrumbs';
import IconFeatureCard from 'component-children/IconFeatureCards/IconFeatureCard/IconFeatureCard';
import { IconFas } from 'component-children/Shared/Icon/Icon';
import moment from 'moment';
import IconSocial from 'component-children/Shared/Icon/IconSocial';
import { getEventListingWithDetails } from 'lib/helpers/listing/event-listing';
import EventListingRendering from 'component-children/Events/EventListing/EventListing';
import { getLayoutLanguage as getLayoutLanguage_e728d7af8daa9d8203279e5961ea194a0b909329 } from 'lib/helpers/language';
import { getDateRange, isNullishDateTime, getLocalizedFormattedDate } from 'lib/helpers/time-date-helper';
import { SocialShare } from 'component-children/Shared/SocialShare/SocialShare';
import { EventMetadata } from 'component-children/Events/EventPage/EventMetadata';
import { getLocationData } from 'lib/helpers/location';
import { EventBodySponsors } from 'component-children/Events/EventPage/EventBodySponsors';
import { mockProfile, mockSponsor } from 'lib/helpers/storybook/mock';
import { EventBodyStaffProfile } from 'component-children/Events/EventPage/EventBodyStaffProfile';
import { getItemPath, getItemPathString } from 'lib/helpers/item-path';
import { EventCardDateBlock } from 'component-children/Shared/Event/EventCardDateBlock';
import { EventCardHeader } from 'component-children/Shared/Event/EventCardHeader';
import { EventCardDetails } from 'component-children/Shared/Event/EventCardDetails';
import { getPageCategories } from 'lib/helpers/page-category';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { ContainerProvider, useContainer } from 'lib/hooks/useContainer';
import { BackgroundImage } from 'component-children/Shared/BackgroundImage/BackgroundImage';
import CardCarousel from 'component-children/Cards/CardCarousel/CardCarousel';
import CardBanner from 'component-children/Cards/CardBanner/CardBanner';
import Card from 'component-children/Cards/Card/Card';
import VideoBanner from 'component-children/Banners/VideoBanner/VideoBanner';
import TextBanner from 'component-children/Banners/TextBanner/TextBanner';
import SplitBanner from 'component-children/Banners/SplitBanner/SplitBanner';
import ContainedSplitBanner from 'component-children/Banners/SplitBanner/ContainedSplitBanner';
import HeroBanner from 'component-children/Banners/HeroBanner/HeroBanner';
import ContentBanner from 'component-children/Banners/ContentBanner/ContentBanner';
import { sortByDatePublished } from 'lib/helpers/sort';
import { DefaultRendering, VerticalListRendering } from 'component-children/Articles/LatestArticleGrid/LatestArticleGrid';
import { getVariantFromRendering, getArticlesByVariant } from 'lib/helpers/listing/article-listing';
import ArticleListingRendering from 'component-children/Articles/ArticleListing/ArticleListing';
import { NewsMetadata, InsightsMetadata, ArticleMetadata } from 'component-children/Articles/ArticlePage/ArticleMetadata';
import ArticleFooter from 'component-children/Articles/ArticleFooter/ArticleFooter';
import ArticleBanner from 'component-children/Articles/ArticleBanner/ArticleBanner';
import ContainedArticleBanner from 'component-children/Articles/ArticleBanner/ContainedArticleBanner';
import { useSession } from 'next-auth/react';
import AccordionDrawer from 'component-children/Accordions/AccordionDrawer/AccordionDrawer';
import Accordion from 'component-children/Accordions/Accordion/Accordion';

const importMap = [
  {
    module: 'react',
    exports: [
      { name: 'useCallback', value: useCallback },
      { name: 'useMemo', value: useMemo },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'useState', value: useState },
      { name: 'startTransition', value: startTransition },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'react-dom/client',
    exports: [
      { name: 'createRoot', value: createRoot },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'next/script',
    exports: [
      { name: 'default', value: Script },
    ]
  },
  {
    module: 'component-children/Shared/Frame/Frame',
    exports: [
      { name: 'default', value: Frame },
    ]
  },
  {
    module: 'component-children/Shared/Containers/ContainedWrapper',
    exports: [
      { name: 'ContainedWrapper', value: ContainedWrapper },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'CdpHelper', value: CdpHelper },
    ]
  },
  {
    module: 'lib/hooks/useTranslation',
    exports: [
      { name: 'useTranslation', value: useTranslation },
    ]
  },
  {
    module: 'lib/hooks/useFrame',
    exports: [
      { name: 'useFrame', value: useFrame },
      { name: 'FrameProvider', value: FrameProvider },
    ]
  },
  {
    module: 'lib/graphql-client',
    exports: [
      { name: 'getGraphQlClient', value: getGraphQlClient },
    ]
  },
  {
    module: 'lib/graphql/id',
    exports: [
      { name: 'BUSINESS_PROFILE_TEMPLATE_ID', value: BUSINESS_PROFILE_TEMPLATE_ID },
      { name: 'NEWS_TEMPLATE_ID', value: NEWS_TEMPLATE_ID },
      { name: 'INSIGHTS_TEMPLATE_ID', value: INSIGHTS_TEMPLATE_ID },
      { name: 'LANDING_PAGE_TEMPLATE_ID', value: LANDING_PAGE_TEMPLATE_ID },
      { name: 'HEADER_CHILD_ID', value: HEADER_CHILD_ID },
      { name: 'HEADER_LINK_GROUP_ID', value: HEADER_LINK_GROUP_ID },
      { name: 'HEADER_LINK_ID', value: HEADER_LINK_ID },
      { name: 'FOOTER_SOCIAL_LINK_TEMPLATE_ID', value: FOOTER_SOCIAL_LINK_TEMPLATE_ID },
      { name: 'FOOTER_LINK_TEMPLATE_ID', value: FOOTER_LINK_TEMPLATE_ID },
      { name: 'ARTICLE_TEMPLATE_ID', value: ARTICLE_TEMPLATE_ID },
    ]
  },
  {
    module: 'lib/const',
    exports: [
      { name: 'PRIMARY_THEME', value: PRIMARY_THEME },
      { name: 'TERTIARY_THEME', value: TERTIARY_THEME },
      { name: 'SECONDARY_THEME', value: SECONDARY_THEME },
    ]
  },
  {
    module: 'lib/helpers',
    exports: [
      { name: 'getLayoutLanguage', value: getLayoutLanguage },
      { name: 'getSiteName', value: getSiteName },
      { name: 'fetchSiteRootInfo', value: fetchSiteRootInfo },
      { name: 'contentRootIdNullChecker', value: contentRootIdNullChecker },
      { name: 'extractHashParams', value: extractHashParams },
      { name: 'mergeHashParams', value: mergeHashParams },
      { name: 'placeholderGenerator', value: placeholderGenerator },
      { name: 'cn', value: cn_ad38580a4d9ab18fff637eb37486c819409ee6c0 },
      { name: 'pageEditCheck', value: pageEditCheck },
      { name: 'getPeoplePageDisplayName', value: getPeoplePageDisplayName },
      { name: 'downloadICS', value: downloadICS },
      { name: 'normalizeSxaTags', value: normalizeSxaTags },
    ]
  },
  {
    module: 'graphql/generated/graphql-documents',
    exports: [
      { name: 'GetBusinessProfiles', value: GetBusinessProfiles },
      { name: 'GetProductDocuments', value: GetProductDocuments },
      { name: 'GetTertiaryNavigation', value: GetTertiaryNavigation },
      { name: 'GetItemById', value: GetItemById },
      { name: 'GetSideNavigation', value: GetSideNavigation },
      { name: 'GetHeaderNavigation', value: GetHeaderNavigation },
      { name: 'GetContentTreeNavigation', value: GetContentTreeNavigation },
      { name: 'GetFooterLegalSocialLinks', value: GetFooterLegalSocialLinks },
      { name: 'GetFooterColumnLinks', value: GetFooterColumnLinks },
      { name: 'GetLatestArticles', value: GetLatestArticles },
      { name: 'GetLatestInsights', value: GetLatestInsights },
      { name: 'GetLatestNews', value: GetLatestNews },
    ]
  },
  {
    module: 'component-children/WhereToBuy/StoreListItem',
    exports: [
      { name: 'StoreListItem', value: StoreListItem },
    ]
  },
  {
    module: 'component-children/WhereToBuy/LoadMoreButton',
    exports: [
      { name: 'LoadMoreButton', value: LoadMoreButton },
    ]
  },
  {
    module: 'component-children/Tabs/TabsContainer/TabsContainer',
    exports: [
      { name: 'TabsContainer', value: TabsContainer },
    ]
  },
  {
    module: 'lib/helpers/tabs',
    exports: [
      { name: 'TAB_LAYOUTS', value: TAB_LAYOUTS },
    ]
  },
  {
    module: 'component-children/Tabs/TabItem/TabItem',
    exports: [
      { name: 'TabItem', value: TabItem },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'WidgetsProvider', value: WidgetsProvider },
    ]
  },
  {
    module: 'src/widgets/SearchResults/SimplePageListingWithFiltersResults',
    exports: [
      { name: 'default', value: SimplePageListingWithFiltersWidget },
    ]
  },
  {
    module: 'lib/const/search-const',
    exports: [
      { name: 'SEARCH_CONFIG', value: SEARCH_CONFIG },
    ]
  },
  {
    module: 'src/components/Search/NoWidgetIdError',
    exports: [
      { name: 'NoWidgetIdError', value: NoWidgetIdError },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'src/widgets/SearchResults/GlobalSearch/index',
    exports: [
      { name: 'default', value: GlobalSearchComponentWidget },
    ]
  },
  {
    module: 'src/widgets/SearchResults/ProductSearch/index',
    exports: [
      { name: 'default', value: ProductSearchWidget },
    ]
  },
  {
    module: 'src/widgets/SearchResults/PeopleSearch',
    exports: [
      { name: 'default', value: PeopleSearchComponentWidget },
    ]
  },
  {
    module: 'src/widgets/SearchResults/SearchListingWithFiltersResults',
    exports: [
      { name: 'default', value: SearchListingWithFiltersWidget },
    ]
  },
  {
    module: 'lib/helpers/article-variants',
    exports: [
      { name: 'ARTICLE_VARIANTS', value: ARTICLE_VARIANTS },
    ]
  },
  {
    module: 'src/widgets/SearchResults/KnowledgeCenterSearch',
    exports: [
      { name: 'default', value: KnowledgeCenterSearchWidget },
    ]
  },
  {
    module: 'src/widgets/SearchResults/EventListingWithFiltersResults',
    exports: [
      { name: 'default', value: EventListingWithFiltersWidget },
    ]
  },
  {
    module: 'src/widgets/SearchResults/ArticleListingWithFiltersResults',
    exports: [
      { name: 'default', value: ArticleListingWithFiltersWidget },
    ]
  },
  {
    module: 'component-children/Product/ProductTechSpecs/ProductTechSpecs',
    exports: [
      { name: 'ProductTechSpecs', value: ProductTechSpecs },
    ]
  },
  {
    module: 'component-children/Product/ProductResources/ProductResources',
    exports: [
      { name: 'ProductResources', value: ProductResources },
    ]
  },
  {
    module: 'component-children/Product/ProductOverview/ProductOverview',
    exports: [
      { name: 'ProductOverview', value: ProductOverview },
    ]
  },
  {
    module: 'component-children/Product/ProductOrderingInfo/ProductOrderingInfo',
    exports: [
      { name: 'ProductOrderingInfo', value: ProductOrderingInfo },
    ]
  },
  {
    module: 'component-children/Product/ProductHeader/ProductHeader',
    exports: [
      { name: 'default', value: ProductHeader },
    ]
  },
  {
    module: 'component-children/Product/ProductHeader/ProductMetaData',
    exports: [
      { name: 'default', value: ProductMetaData },
    ]
  },
  {
    module: 'component-children/Product/ProductDocuments/ProductDocuments',
    exports: [
      { name: 'ProductDocuments', value: ProductDocuments },
    ]
  },
  {
    module: 'component-children/People/PersonProfile/PersonProfile',
    exports: [
      { name: 'default', value: PersonProfileRendering },
    ]
  },
  {
    module: 'component-children/Page Content/SimplePageListing/SimplePageListing',
    exports: [
      { name: 'default', value: SimplePageListingRendering },
    ]
  },
  {
    module: 'lib/helpers/listing/page-listing',
    exports: [
      { name: 'getPageListingWithDetails', value: getPageListingWithDetails },
    ]
  },
  {
    module: 'lib/helpers/classname',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'component-children/Shared/Containers/FullWidthWrapper',
    exports: [
      { name: 'FullWidthWrapper', value: FullWidthWrapper },
    ]
  },
  {
    module: 'lib/hooks/useImage',
    exports: [
      { name: 'useImage', value: useImage },
    ]
  },
  {
    module: 'component-children/Shared/Containers/Wrapper',
    exports: [
      { name: 'Wrapper', value: Wrapper },
    ]
  },
  {
    module: 'component-children/Page Content/CTABlock/CTABlock',
    exports: [
      { name: 'default', value: CTABlock },
    ]
  },
  {
    module: 'component-children/Page Content/ContentBlock/ContentBlockImageLeft',
    exports: [
      { name: 'ContentBlockImageLeft', value: ContentBlockImageLeft },
    ]
  },
  {
    module: 'component-children/Page Content/ContentBlock/ContentBlock',
    exports: [
      { name: 'default', value: ContentBlock },
    ]
  },
  {
    module: 'component-children/Shared/Button/Button',
    exports: [
      { name: 'Button', value: Button },
      { name: 'default', value: Button_e5ef0f25383a4b5a7bc1027fc8ac4045058cb2fe },
    ]
  },
  {
    module: 'component-children/Page Content/AlertBanner/AlertBanner',
    exports: [
      { name: 'fetchAlertBannerData', value: fetchAlertBannerData },
      { name: 'AlertBanner', value: AlertBanner },
      { name: 'AlertBannerEditRendering', value: AlertBannerEditRendering },
    ]
  },
  {
    module: 'lib/i18n/i18n-config',
    exports: [
      { name: 'mainLanguage', value: mainLanguage },
      { name: 'availableLanguages', value: availableLanguages },
    ]
  },
  {
    module: 'lib/hooks/useAccordion',
    exports: [
      { name: 'AccordionProvider', value: AccordionProvider },
      { name: 'useAccordion', value: useAccordion },
    ]
  },
  {
    module: 'component-children/Shared/Animation/AccordionMotion',
    exports: [
      { name: 'AccordionMotion', value: AccordionMotion },
    ]
  },
  {
    module: 'component-children/Shared/Button/ButtonIcon',
    exports: [
      { name: 'default', value: ButtonIcon },
    ]
  },
  {
    module: 'component-children/Navigation/PersonaSwitcher/PersonaSwitcher',
    exports: [
      { name: 'PersonaSwitcher', value: PersonaSwitcher },
    ]
  },
  {
    module: 'component-children/Navigation/Login/Login',
    exports: [
      { name: 'Login', value: Login },
    ]
  },
  {
    module: 'lib/helpers/auth',
    exports: [
      { name: 'isAuthEnabled', value: isAuthEnabled },
    ]
  },
  {
    module: 'lib/helpers/site-config-helpers',
    exports: [
      { name: 'fetchAuthConfig', value: fetchAuthConfig },
    ]
  },
  {
    module: 'component-children/Navigation/LanguageSwitcher/LanguageSwitcher',
    exports: [
      { name: 'LanguageSwitcher', value: LanguageSwitcher },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'component-children/Navigation/Header/PageList',
    exports: [
      { name: 'PageList', value: PageList },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: 'component-children/Search/SearchModal',
    exports: [
      { name: 'SearchModal', value: SearchModal },
    ]
  },
  {
    module: 'component-children/Navigation/Breadcrumbs/Breadcrumbs',
    exports: [
      { name: 'getPagePathList', value: getPagePathList },
      { name: 'default', value: BreadcrumbsRendering },
    ]
  },
  {
    module: 'component-children/IconFeatureCards/IconFeatureCard/IconFeatureCard',
    exports: [
      { name: 'default', value: IconFeatureCard },
    ]
  },
  {
    module: 'component-children/Shared/Icon/Icon',
    exports: [
      { name: 'IconFas', value: IconFas },
    ]
  },
  {
    module: 'moment',
    exports: [
      { name: 'default', value: moment },
    ]
  },
  {
    module: 'component-children/Shared/Icon/IconSocial',
    exports: [
      { name: 'default', value: IconSocial },
    ]
  },
  {
    module: 'lib/helpers/listing/event-listing',
    exports: [
      { name: 'getEventListingWithDetails', value: getEventListingWithDetails },
    ]
  },
  {
    module: 'component-children/Events/EventListing/EventListing',
    exports: [
      { name: 'default', value: EventListingRendering },
    ]
  },
  {
    module: 'lib/helpers/language',
    exports: [
      { name: 'getLayoutLanguage', value: getLayoutLanguage_e728d7af8daa9d8203279e5961ea194a0b909329 },
    ]
  },
  {
    module: 'lib/helpers/time-date-helper',
    exports: [
      { name: 'getDateRange', value: getDateRange },
      { name: 'isNullishDateTime', value: isNullishDateTime },
      { name: 'getLocalizedFormattedDate', value: getLocalizedFormattedDate },
    ]
  },
  {
    module: 'component-children/Shared/SocialShare/SocialShare',
    exports: [
      { name: 'SocialShare', value: SocialShare },
    ]
  },
  {
    module: 'component-children/Events/EventPage/EventMetadata',
    exports: [
      { name: 'EventMetadata', value: EventMetadata },
    ]
  },
  {
    module: 'lib/helpers/location',
    exports: [
      { name: 'getLocationData', value: getLocationData },
    ]
  },
  {
    module: 'component-children/Events/EventPage/EventBodySponsors',
    exports: [
      { name: 'EventBodySponsors', value: EventBodySponsors },
    ]
  },
  {
    module: 'lib/helpers/storybook/mock',
    exports: [
      { name: 'mockProfile', value: mockProfile },
      { name: 'mockSponsor', value: mockSponsor },
    ]
  },
  {
    module: 'component-children/Events/EventPage/EventBodyStaffProfile',
    exports: [
      { name: 'EventBodyStaffProfile', value: EventBodyStaffProfile },
    ]
  },
  {
    module: 'lib/helpers/item-path',
    exports: [
      { name: 'getItemPath', value: getItemPath },
      { name: 'getItemPathString', value: getItemPathString },
    ]
  },
  {
    module: 'component-children/Shared/Event/EventCardDateBlock',
    exports: [
      { name: 'EventCardDateBlock', value: EventCardDateBlock },
    ]
  },
  {
    module: 'component-children/Shared/Event/EventCardHeader',
    exports: [
      { name: 'EventCardHeader', value: EventCardHeader },
    ]
  },
  {
    module: 'component-children/Shared/Event/EventCardDetails',
    exports: [
      { name: 'EventCardDetails', value: EventCardDetails },
    ]
  },
  {
    module: 'lib/helpers/page-category',
    exports: [
      { name: 'getPageCategories', value: getPageCategories },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'lib/hooks/useContainer',
    exports: [
      { name: 'ContainerProvider', value: ContainerProvider },
      { name: 'useContainer', value: useContainer },
    ]
  },
  {
    module: 'component-children/Shared/BackgroundImage/BackgroundImage',
    exports: [
      { name: 'BackgroundImage', value: BackgroundImage },
    ]
  },
  {
    module: 'component-children/Cards/CardCarousel/CardCarousel',
    exports: [
      { name: 'default', value: CardCarousel },
    ]
  },
  {
    module: 'component-children/Cards/CardBanner/CardBanner',
    exports: [
      { name: 'default', value: CardBanner },
    ]
  },
  {
    module: 'component-children/Cards/Card/Card',
    exports: [
      { name: 'default', value: Card },
    ]
  },
  {
    module: 'component-children/Banners/VideoBanner/VideoBanner',
    exports: [
      { name: 'default', value: VideoBanner },
    ]
  },
  {
    module: 'component-children/Banners/TextBanner/TextBanner',
    exports: [
      { name: 'default', value: TextBanner },
    ]
  },
  {
    module: 'component-children/Banners/SplitBanner/SplitBanner',
    exports: [
      { name: 'default', value: SplitBanner },
    ]
  },
  {
    module: 'component-children/Banners/SplitBanner/ContainedSplitBanner',
    exports: [
      { name: 'default', value: ContainedSplitBanner },
    ]
  },
  {
    module: 'component-children/Banners/HeroBanner/HeroBanner',
    exports: [
      { name: 'default', value: HeroBanner },
    ]
  },
  {
    module: 'component-children/Banners/ContentBanner/ContentBanner',
    exports: [
      { name: 'default', value: ContentBanner },
    ]
  },
  {
    module: 'lib/helpers/sort',
    exports: [
      { name: 'sortByDatePublished', value: sortByDatePublished },
    ]
  },
  {
    module: 'component-children/Articles/LatestArticleGrid/LatestArticleGrid',
    exports: [
      { name: 'DefaultRendering', value: DefaultRendering },
      { name: 'VerticalListRendering', value: VerticalListRendering },
    ]
  },
  {
    module: 'lib/helpers/listing/article-listing',
    exports: [
      { name: 'getVariantFromRendering', value: getVariantFromRendering },
      { name: 'getArticlesByVariant', value: getArticlesByVariant },
    ]
  },
  {
    module: 'component-children/Articles/ArticleListing/ArticleListing',
    exports: [
      { name: 'default', value: ArticleListingRendering },
    ]
  },
  {
    module: 'component-children/Articles/ArticlePage/ArticleMetadata',
    exports: [
      { name: 'NewsMetadata', value: NewsMetadata },
      { name: 'InsightsMetadata', value: InsightsMetadata },
      { name: 'ArticleMetadata', value: ArticleMetadata },
    ]
  },
  {
    module: 'component-children/Articles/ArticleFooter/ArticleFooter',
    exports: [
      { name: 'default', value: ArticleFooter },
    ]
  },
  {
    module: 'component-children/Articles/ArticleBanner/ArticleBanner',
    exports: [
      { name: 'default', value: ArticleBanner },
    ]
  },
  {
    module: 'component-children/Articles/ArticleBanner/ContainedArticleBanner',
    exports: [
      { name: 'default', value: ContainedArticleBanner },
    ]
  },
  {
    module: 'next-auth/react',
    exports: [
      { name: 'useSession', value: useSession },
    ]
  },
  {
    module: 'component-children/Accordions/AccordionDrawer/AccordionDrawer',
    exports: [
      { name: 'default', value: AccordionDrawer },
    ]
  },
  {
    module: 'component-children/Accordions/Accordion/Accordion',
    exports: [
      { name: 'default', value: Accordion },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
