---
ID: "e50be2ec-0b7e-415f-8074-874f9c657675"
Parent: "3335947d-273b-40b8-9a9a-b5fdb7eb0ed8"
Template: "3335947d-273b-40b8-9a9a-b5fdb7eb0ed8"
Path: /sitecore/templates/Project/Common/Pages/Common Product Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250825T174545Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\daustin@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\daustin@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "623d2850-eb3f-4ff8-b907-8677f971ad89"
    - ID: "98a91543-0830-4b7f-8a29-f1ffddaa7f18"
      Hint: productName
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251231T170519Z
