---
ID: "d3c2ae93-1ea7-4c46-b6c4-22708a561cc0"
Parent: "f9afe766-7656-4429-a503-94effe72296f"
Template: "f9afe766-7656-4429-a503-94effe72296f"
Path: /sitecore/templates/Feature/Common/Events/EventListing/EventListing/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a2891790-eca7-4782-9d58-15babf37736b"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T201621Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "14cbd2b7-f2fb-4a81-b375-37762eba2e6c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Event Listing Heading
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124931Z
