---
ID: "6b39d51d-1384-4a85-8b76-ccff38bdac3c"
Parent: "61731543-ba62-4104-a1d4-04aa3c9feeab"
Template: "61731543-ba62-4104-a1d4-04aa3c9feeab"
Path: /sitecore/templates/Feature/Common/Navigation/TertiaryNav/TertiaryNav Parameters/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "7bed1b9e-5b2b-4396-af9e-5c9f5fffeaf6"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ebe51fce-e974-44f2-95af-cda7fa93e52f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124934Z
