---
ID: "e7579347-1fcd-41d3-9114-0e642b1ea9c6"
Parent: "7f2180ab-7b3d-41c1-a7e1-beb20e85fdc3"
Template: "7f2180ab-7b3d-41c1-a7e1-beb20e85fdc3"
Path: /sitecore/templates/Foundation/Common/Profile Manager/Involvement/Involvement Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/32x32/folder_blue.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3374FC7C-BC84-45F6-A9DC-36ED93C75934}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "d5896a1c-ed92-42e7-bfdd-13ad96a4dc24"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251105T173227Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jmurphy@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jmurphy@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f56d1806-a177-4947-8acf-cfe4b35e8f39"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jmurphy@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251106T161002Z
