---
ID: "356d0a2a-5408-4c45-89e0-00ea023a9c42"
Parent: "cbc49d14-a75f-4acd-8e3b-bd1e3d8f6b20"
Template: "cbc49d14-a75f-4acd-8e3b-bd1e3d8f6b20"
Path: /sitecore/templates/Foundation/Common/Rendering Parameters/Config Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C08FDF7E-7C56-4BF6-A7AC-238DB1329334}
    {CBC49D14-A75F-4ACD-8E3B-BD1E3D8F6B20}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "2313e6cf-99e8-427c-bebf-8a543e0a549c"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241107T144415Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\edimech@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\edimech@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a5d050fd-d169-409f-96b1-9447f91b3fb9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jflheureux@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250513T214545Z
