// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { cn } from 'lib/helpers';
import { useTranslation } from 'lib/hooks/useTranslation';

type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItems: number;
  totalItemsReturned: number;
  className?: string;
};
const QueryResultsSummary = ({
  currentPage,
  itemsPerPage,
  totalItems,
  totalItemsReturned,
  className,
}: QueryResultsSummaryProps) => {
  const { t } = useTranslation();

  const startItem = itemsPerPage * (currentPage - 1) + 1;
  const endItem = itemsPerPage * (currentPage - 1) + totalItemsReturned;

  return (
    <p className={cn('copy-sm text-content', className)}>
      {t('Showing {start} - {end} of {total} results')
        .replace('{start}', startItem.toString())
        .replace('{end}', endItem.toString())
        .replace('{total}', totalItems.toString())}
    </p>
  );
};

export default QueryResultsSummary;
