---
ID: "cc3e7d9a-672c-4585-94fd-1ed18ce55c7f"
Parent: "45841e48-3025-45c1-9948-8eb85a908615"
Template: "6d1cd897-1936-4a3a-a511-289a94c2a7b1"
Path: /sitecore/content/Sites/main/Dictionary/R/ResourcesAndApplications
SharedFields:
- ID: "580c75a8-c01a-4580-83cb-987776ceb3af"
  Hint: Key
  Value: Resources & Applications
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "1d041a2e-d8b7-484a-a0bb-e5ae0c76601c"
Languages:
- Language: en
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Resources & Applications
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "9cd1d6e7-0045-497f-9695-b0fcf781db27"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251126T175356Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "370dc91f-ae8b-4c90-b6c5-cffbd04b1142"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251126T175402Z
- Language: "fr-CA"
  Fields:
  - ID: "2ba3454a-9a9c-4cdf-a9f8-107fd484eb6e"
    Hint: Phrase
    Value: Ressources et applications
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "0e65334d-3d37-4b64-ac46-a71e03aa20bd"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251126T175457Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d610156b-403f-411b-adc8-71bf7f8d01a0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\gencabo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251126T175501Z
