---
ID: "f4de9f0d-d536-4e68-b313-be2ce9459606"
Parent: "32f1fc9d-77d3-4ee8-b21c-5109f7f9b4cf"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Sites/main/Presentation/Headless Variants/EventBody/Default
SharedFields:
- ID: "696c70e2-eb4e-425d-81e4-802bab6a03cf"
  Hint: AllowedInTemplates
  Value: "{B1DF3406-1061-4200-A833-16650B0C16EB}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241120T220055Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c17acb15-21f1-4abc-88cd-50c47f95ed69"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241120T220100Z
