---
ID: "ca074422-82b0-473b-b969-eeeb4bb722f8"
Parent: "5d09e770-1aea-492f-aec8-bb20ea81a31a"
Template: "5d09e770-1aea-492f-aec8-bb20ea81a31a"
Path: /sitecore/templates/Feature/Common/Events/EventListing/EventListing Parameters/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a553cb12-405d-41ca-89fc-4d3beea9a0e3"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4638c95d-e836-4100-9e1a-09d669444238"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124931Z
