// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 16:04:18 GMT-0400 (Eastern Daylight Saving Time)

import { CardViewSwitcherStyled } from './styled';

type CardViewSwitcherProps = {
  onToggle: (value: string) => void;
  defaultCardView: 'list' | 'grid';
  GridIcon: React.FC;
  ListIcon: React.FC;
};

const CardViewSwitcherComponent = ({
  onToggle,
  defaultCardView,
  GridIcon,
  ListIcon,
}: CardViewSwitcherProps) => {
  return (
    <CardViewSwitcherStyled.Root onValueChange={onToggle} defaultValue={defaultCardView}>
      <CardViewSwitcherStyled.Item value="grid" aria-label="Grid View">
        <GridIcon />
      </CardViewSwitcherStyled.Item>
      <CardViewSwitcherStyled.Item value="list" aria-label="List View">
        <ListIcon />
      </CardViewSwitcherStyled.Item>
    </CardViewSwitcherStyled.Root>
  );
};

export default CardViewSwitcherComponent;
