// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 16:04:18 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { CardViewSwitcher, theme } from '@sitecore-search/ui';

const CardViewSwitcherRoot = styled(CardViewSwitcher.Root)`
  display: inline-flex;
  background-color: transparent;
`;

const CardViewSwitcherItem = styled(CardViewSwitcher.Item)`
  all: unset;
  align-items: center;
  background-color: transparent;
  border: 2px solid rgb(var(--text) / 0.2);
  border-radius: ${theme.vars.border.radius};
  color: rgb(var(--text));
  display: flex;
  height: 30px;
  justify-content: center;
  margin-left: 8px;
  width: 30px;
  cursor: pointer;

  &:first-child {
    margin-left: 0;
  }

  &:hover {
    background-color: rgb(var(--text) / 0.05);
    border-color: rgb(var(--text) / 0.4);
  }
  &[data-state='on'] {
    background-color: rgb(var(--next-secondary-bg));
    color: rgb(var(--next-secondary-text));
    border-color: rgb(var(--next-secondary-bg));
  }

  &:focus {
    position: relative;
    border: solid 2px rgb(var(--text));
  }
`;

export const CardViewSwitcherStyled = {
  Root: CardViewSwitcherRoot,
  Item: CardViewSwitcherItem,
};
