// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { useState, useMemo } from 'react';
import { useSearchResultsActions } from '@sitecore-search/react';
import { Select } from '@sitecore-search/ui';

import { SelectContent, SelectItem, SelectTrigger, SelectValue, SelectViewport } from './styled';
import { GlobalSearchProps } from 'lib/types/components/Search/global-search';

type ResultsPerPageProps = {
  defaultItemsPerPage: number;
  pageSizeText: string;
  globalSearchFields: GlobalSearchProps;
  className?: string;
};
const ResultsPerPage = ({
  pageSizeText,
  defaultItemsPerPage,
  globalSearchFields,
  className,
}: ResultsPerPageProps) => {
  const [selectedValue, setSelectedValue] = useState(String(defaultItemsPerPage));
  const { onResultsPerPageChange } = useSearchResultsActions();

  const options = useMemo(() => {
    return Array.from({ length: 4 }, (_, index) => {
      const value =
        index === 0 ? 5 : (globalSearchFields.fields.PageSizeCount?.value as number) * index;
      return { value: String(value), label: String(value) };
    });
  }, [globalSearchFields.fields.PageSizeCount?.value]);

  const handleValueChange = (v: string) => {
    setSelectedValue(v);
    onResultsPerPageChange({
      numItems: Number(v),
    });
  };

  return (
    <div className={className}>
      <label className="copy-sm">{pageSizeText}</label>
      <Select.Root value={selectedValue} onValueChange={handleValueChange}>
        <SelectTrigger>
          <SelectValue>{selectedValue}</SelectValue>
          <Select.Icon />
        </SelectTrigger>
        <SelectContent
          side="bottom"
          align="start"
          sideOffset={0}
          avoidCollisions={false}
          position="popper"
        >
          <SelectViewport asChild={false}>
            {options.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectViewport>
        </SelectContent>
      </Select.Root>
    </div>
  );
};

export default ResultsPerPage;
