---
ID: "40d7361f-6ccb-4447-ae61-5eb329dc399f"
Parent: "029a814e-9596-4b17-8935-cad60f36a2b8"
Template: "029a814e-9596-4b17-8935-cad60f36a2b8"
Path: /sitecore/templates/Feature/Common/Search/WhereToBuy/WhereToBuy/__Standard Values
SharedFields:
- ID: "0834b5dd-2db4-4511-8a9d-c086826d2ceb"
  Hint: defaultMapZoomLevel
  Value: 4
- ID: "1c9a5a42-f62f-4590-8023-f5ec374685a0"
  Hint: defaultMapCenterLatitude
  Value: 51.0447
- ID: "33f2838d-61aa-4013-a1b7-5a5272e08568"
  Hint: userLocationIndicatorColor
  Value: D12F36
- ID: "66b58725-b0ca-4c2a-9f93-82c7a63c4594"
  Hint: defaultMapCenterLongitude
  Value: "-114.0719"
- ID: "6e09397c-f64f-4a97-8ed8-eeeaa1cdab20"
  Hint: userLocationZoomLevel
  Value: 12
- ID: "7a6ac1bf-e26a-46c1-83ae-33001c8655dd"
  Hint: individualLocationMarkerColor
  Value: D12F36
- ID: "94eab11b-4587-4f92-bbf4-b5272714f91e"
  Hint: locationsPerPage
  Value: 10
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "88b9648c-0dae-4fef-83fc-9dabe11ba196"
- ID: "e2868d84-4ec1-456c-8221-0b9f4d1a1da8"
  Hint: userLocationSearchRadius
  Value: 200
- ID: "e971b3e5-41f2-427c-9fce-01a21b51f63a"
  Hint: clusterLocationMarkerBackgroundColor
  Value: #ffffff
- ID: "f39f4b65-2e8c-4323-8c2b-6f909e2548db"
  Hint: businessLocationZoomLevel
  Value: 14
- ID: "f85e0641-c840-4122-8dff-b9c9f35ede77"
  Hint: clusterLocationMarkerTextAndBorderColor
  Value: #000000
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T194809Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a36810d3-b75d-4219-8509-6b96e13f50ba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kparks@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Business Locations
    - ID: "c3c248a3-843e-4b19-a2e6-40d9a1352126"
      Hint: subheading
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250921T152054Z
