// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { keyframes, styled } from 'styled-components';

import { theme } from '@sitecore-search/ui';

const Rotate = keyframes`
  from {
      transform: rotate(0deg);
  }
  to {
      transform: rotate(360deg);
  }
`;

export const LoaderAnimation = styled.svg`
  animation: ${Rotate} 2s linear infinite;
  display: block;
  color: ${theme.vars.palette.text.primary};
  height: 50px;
  margin: auto;
  width: 50px;
`;

export const LoaderContainer = styled.div`
  align-items: center;
  display: flex;
  position: absolute;
  left: 0;
  right: 0;
  height: 100%;
  background-color: rgb(var(--next-primary-bg));
  z-index: 100;
`;
