// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 16:04:18 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { ArticleCard, theme } from '@sitecore-search/ui';

const EventRootStyled = styled(ArticleCard.Root)`
  box-sizing: border-box;
  position: relative;
  width: 100%;
  min-height: 0;
  max-width: 100%;
  display: flex;
`;
const EventImageWrapper = styled.div`
  aspect-ratio: 1/1;
`;

const EventImageStyled = styled(ArticleCard.Image)`
  object-fit: cover;
  object-position: center;
  width: 100%;
  height: 100%;
`;

const EventContentStyled = styled(ArticleCard.Content)`
  display: flex;
  flex-direction: column;
  flex: 1;
`;

const EventTitleStyled = styled(ArticleCard.Title)``;

const EventLinkStyled = styled.a`
  text-decoration: none;
  color: ${theme.vars.palette.text.primary};
  font-size: ${theme.vars.typography.fontSize4.fontSize};
  &:hover {
    text-decoration: underline;
  }
  &:focus {
    text-decoration: underline;
    outline-color: ${theme.vars.palette.grey['800']};
  }
`;

const EventSpan = styled.span`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
`;

const EventSubtitle = styled(ArticleCard.Subtitle)`
  color: ${theme.vars.palette.text.primary};
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  font-weight: ${theme.vars.typography.fontSize3.fontWeight};
  line-height: ${theme.vars.typography.fontSize2.lineHeight};
  bottom: ${theme.vars.spacing.s};
`;

const EventContentTextStyled = styled.div`
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  font-size: ${theme.vars.typography.fontSize1.fontSize};
  line-height: ${theme.vars.typography.fontSize1.lineHeight};
  max-width: 100%;
  overflow-wrap: break-word;
  word-wrap: break-word;
  hyphens: auto;
`;

export const EventCardStyled = {
  Link: EventLinkStyled,
  Content: EventContentStyled,
  ImageWrapper: EventImageWrapper,
  Image: EventImageStyled,
  Title: EventTitleStyled,
  Root: EventRootStyled,
  Span: EventSpan,
  Text: EventContentTextStyled,
  Subtitle: EventSubtitle,
};
