---
ID: "7d76199e-45a7-479c-b3ee-48a995163083"
Parent: "4d7b5935-16fb-4cc9-a19c-bc0e7671ba3c"
Template: "4d7b5935-16fb-4cc9-a19c-bc0e7671ba3c"
Path: /sitecore/templates/Feature/Common/Footer/FooterLegal/FooterLegal Parameters/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "365ead63-212d-4bdc-8bc2-6f5e19008110"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dc8d7723-e2c7-4621-9ae4-9c20e849597d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124932Z
