---
ID: "a869d6d7-66b6-4043-9098-d4bd324e1641"
Parent: "0cc3a0b3-e599-4152-bf32-a59d48b746e3"
Template: "0cc3a0b3-e599-4152-bf32-a59d48b746e3"
Path: /sitecore/templates/Feature/Common/Cards/Card/Card/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c4ed1f32-6355-457a-9bc0-d67c707ec2c3"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "06fe7e7f-2451-47c0-b0cf-dc6bfeca6744"
      Hint: image
      Value: |
        <image mediaid="{FB70BF8B-1254-4326-8FB7-C136E49E68C8}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T200652Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "214bb665-f049-431f-8348-d30bd866639d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Card Heading
    - ID: "d71bc2be-4f73-46f8-808c-86cbe11ad047"
      Hint: body
      Value: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T155751Z
