---
ID: "c907d394-8372-4a96-b789-e78d75b7432e"
Parent: "817348e5-9a0e-437b-9dcf-1f27e771b30c"
Template: "817348e5-9a0e-437b-9dcf-1f27e771b30c"
Path: /sitecore/templates/Feature/Common/Containers/FullWidth/FullWidth/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "8c7abdab-4c4c-46db-a8ef-06245e07ca90"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T201049Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c7325e5b-204a-469e-a065-6df29d8240f4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "bfbb1f8c-0f06-4d81-ae1d-33d63f075859"
      Hint: backgroundImage
      Value: |
        <image mediaid="{FB70BF8B-1254-4326-8FB7-C136E49E68C8}" />
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124930Z
