// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { ArticleCard, theme } from '@sitecore-search/ui';

const ArticleRootStyled = styled(ArticleCard.Root).attrs({
  className: 'article-horizontal-card',
})`
  display: flex;
  box-sizing: border-box;
  position: relative;
  margin-top: ${theme.vars.spacing.m};
  margin-bottom: ${theme.vars.spacing.m};
  flex-direction: row;
  flex-wrap: nowrap;
  width: 100%;
`;

const ArticleTitleStyled = styled(ArticleCard.Title)``;

const ArticleSubtitle = styled(ArticleCard.Subtitle)`
  color: ${theme.vars.palette.text.secondary};
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: ${theme.vars.typography.fontSize3.fontSize};
  font-weight: ${theme.vars.typography.fontSize3.fontWeight};
  line-height: ${theme.vars.typography.fontSize3.lineHeight};
`;

const ArticleContentStyled = styled(ArticleCard.Content)`
  display: flex;
  flex-direction: column;
`;

const ArticleContentTextStyled = styled.div`
  overflow: hidden;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  font-size: ${theme.vars.typography.fontSize};
  line-height: 1.25rem;
`;

const ArticleIdStyled = styled(ArticleCard.Id)`
  font-family: ${theme.vars.typography.fontFamilySystem};
  color: ${theme.vars.palette.primary.main};
  font-size: ${theme.vars.typography.fontSize1.fontSize};
`;

const ArticleLinkStyled = styled.a`
  text-decoration: none;
  color: ${theme.vars.palette.primary.main};
  font-size: ${theme.vars.typography.fontSize4.fontSize};
  &:hover {
    text-decoration: underline;
  }
  &:focus {
    text-decoration: underline;
  }
`;

export const ArticleCardStyled = {
  Link: ArticleLinkStyled,
  Id: ArticleIdStyled,
  Content: ArticleContentStyled,
  Title: ArticleTitleStyled,
  Root: ArticleRootStyled,
  Text: ArticleContentTextStyled,
  Subtitle: ArticleSubtitle,
};
