// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { ArrowLeftIcon, ArrowRightIcon } from '@radix-ui/react-icons';
import { useSearchResultsActions } from '@sitecore-search/react';
import { Pagination } from '@sitecore-search/ui';

import { PaginationStyled } from './styled';

type SearchPaginationProps = {
  currentPage: number;
  totalPages: number;
};

const SearchPagination = ({ currentPage, totalPages }: SearchPaginationProps) => {
  const { onPageNumberChange } = useSearchResultsActions();
  return (
    <PaginationStyled.Root
      currentPage={currentPage}
      defaultCurrentPage={1}
      totalPages={totalPages}
      onPageChange={(page) => onPageNumberChange({ page })}
    >
      <PaginationStyled.PrevPage onClick={(e) => e.preventDefault()}>
        <ArrowLeftIcon />
      </PaginationStyled.PrevPage>
      <PaginationStyled.Pages>
        {(pagination) =>
          Pagination.paginationLayout(pagination, {
            boundaryCount: 1,
            siblingCount: 1,
          }).map(({ page, type }) =>
            type === 'page' ? (
              <PaginationStyled.Page
                key={page}
                aria-label={`Page ${page}`}
                page={page as number}
                onClick={(e) => e.preventDefault()}
              >
                {page}
              </PaginationStyled.Page>
            ) : (
              <span key={type}>...</span>
            )
          )
        }
      </PaginationStyled.Pages>
      <PaginationStyled.NextPage onClick={(e) => e.preventDefault()}>
        <ArrowRightIcon />
      </PaginationStyled.NextPage>
    </PaginationStyled.Root>
  );
};

export default SearchPagination;
