// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { Pagination, theme } from '@sitecore-search/ui';

const PaginationRootStyled = styled(Pagination.Root)`
  color: ${theme.vars.palette.text.primary};
  font-family: ${theme.vars.typography.fontFamilySystem};
  display: flex;
  margin-top: ${theme.vars.spacing.m};
`;
const PaginationPrevPageStyled = styled(Pagination.PrevPage)`
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  cursor: pointer;
  color: ${theme.vars.palette.text.primary};
  margin: 0 5px;
  text-decoration: none;

  &:hover {
    color: ${theme.vars.palette.primary.main};
  }

  &[data-current='true'] {
    color: ${theme.vars.palette.primary.main};
    pointer-events: none;
    text-decoration-line: none;
    display: none;
  }
`;
const PaginationNextPageStyled = styled(Pagination.NextPage)`
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  cursor: pointer;
  color: ${theme.vars.palette.text.primary};
  margin: 0 5px;
  text-decoration: none;

  &:hover {
    color: ${theme.vars.palette.primary.main};
  }

  &[data-current='true'] {
    color: ${theme.vars.palette.primary.main};
    pointer-events: none;
    text-decoration-line: none;
    display: none;
  }
`;
const PaginationFirstPageStyled = styled(Pagination.FirstPage)`
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  cursor: pointer;
  color: ${theme.vars.palette.text.primary};
  margin: 0 5px;
  text-decoration: none;

  &:hover {
    color: ${theme.vars.palette.primary.main};
  }

  &[data-current='true'] {
    color: ${theme.vars.palette.primary.main};
    pointer-events: none;
    text-decoration-line: none;
    display: none;
  }
`;
const PaginationLastPageStyled = styled(Pagination.LastPage)`
  font-size: ${theme.vars.typography.fontSize2.fontSize};
  cursor: pointer;
  color: ${theme.vars.palette.text.primary};
  margin: 0 5px;
  text-decoration: none;

  &:hover {
    color: ${theme.vars.palette.primary.main};
  }

  &[data-current='true'] {
    color: ${theme.vars.palette.primary.main};
    pointer-events: none;
    text-decoration-line: none;
  }
`;
const PaginationPageStyled = styled(Pagination.Page)`
  cursor: pointer;
  color: ${theme.vars.palette.text.primary};
  margin: 0 5px;
  text-decoration: none;

  &:hover {
    color: ${theme.vars.palette.primary.main};
  }

  &[data-current='true'] {
    color: ${theme.vars.palette.primary.main};
    pointer-events: none;
    text-decoration-line: none;
  }
`;
const PaginationPagesStyled = styled(Pagination.Pages)``;

export const PaginationStyled = {
  Root: PaginationRootStyled,
  PrevPage: PaginationPrevPageStyled,
  NextPage: PaginationNextPageStyled,
  FirstPage: PaginationFirstPageStyled,
  LastPage: PaginationLastPageStyled,
  Page: PaginationPageStyled,
  Pages: PaginationPagesStyled,
};
