// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { useMemo } from 'react';
import type { SearchResponseSortChoice } from '@sitecore-search/data';
import { useSearchResultsActions } from '@sitecore-search/react';
import { SortSelect } from '@sitecore-search/ui';

import { SortSelectStyled } from './styled';

type SortOrderProps = {
  options: Array<SearchResponseSortChoice>;
  selected: string;
};

const SortOrder = ({ options, selected }: SortOrderProps) => {
  const selectedSortIndex = options.findIndex((s) => s.name === selected);
  const { onSortChange } = useSearchResultsActions();
  // Calculate minimum width based on longest option label
  const minWidth = useMemo(() => {
    const longestLabel = options.reduce((longest, option) => {
      return option.label.length > longest.length ? option.label : longest;
    }, '');
    // Rough estimate: 9px per character + 60px for padding, gap, and arrow icon
    return Math.max(200, longestLabel.length * 9 + 30);
  }, [options]);

  return (
    <SortSelect.Root value={options[selectedSortIndex]?.name} onValueChange={onSortChange}>
      <SortSelectStyled.Trigger className="w-full sm:w-auto" style={{ minWidth: `${minWidth}px` }}>
        <SortSelectStyled.SelectValue>
          {selectedSortIndex > -1 ? options[selectedSortIndex].label : ''}
        </SortSelectStyled.SelectValue>
        <SortSelectStyled.Icon />
      </SortSelectStyled.Trigger>
      <SortSelectStyled.Content
        side="bottom"
        align="start"
        sideOffset={0}
        avoidCollisions={false}
        position="popper"
      >
        <SortSelectStyled.Viewport asChild={false}>
          {options.map((option: Record<string, unknown>) => (
            <SortSelectStyled.Option
              value={option as { name: string; label: string }}
              key={option.name as string}
            >
              <SortSelectStyled.OptionText>{option.label as string}</SortSelectStyled.OptionText>
            </SortSelectStyled.Option>
          ))}
        </SortSelectStyled.Viewport>
      </SortSelectStyled.Content>
    </SortSelect.Root>
  );
};

export default SortOrder;
