// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { SortSelect, theme } from '@sitecore-search/ui';

const SortSelectTriggerStyled = styled(SortSelect.Trigger)`
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: space-between;
  gap: 4px;
  background-color: rgb(var(--bg));
  height: 40px;
  padding: 12px 16px;
  font-family: ${theme.vars.typography.fontFamilySystem};
  border: 1px solid rgb(var(--text) / 0.2);
  min-width: 200px;
  font-size: 14px;

  &:focus {
    outline: none;
    border-color: ${theme.vars.palette.primary.main};
  }
  &[data-state='open'] {
    border-color: ${theme.vars.palette.primary.main};
  }
`;

const SortSelectContentStyled = styled(SortSelect.Content)`
  background-color: rgb(var(--bg));
  overflow: visible;
  box-shadow: 2px 2px 4px rgb(var(--text) / 0.15);
  z-index: 100;
  border: 1px solid rgb(var(--text) / 0.2);
  border-top: none;
  min-width: var(--radix-select-trigger-width);
  width: var(--radix-select-trigger-width);
  padding: 0;
  &:focus-within {
    border-color: ${theme.vars.palette.primary.dark};
  }
`;

const SortSelectViewportStyled = styled(SortSelect.Viewport)`
  padding: 4px;
  z-index: 999;
  width: 100%;
`;

const SortSelectOptionStyled = styled(SortSelect.Option)`
  display: flex;
  align-items: center;
  justify-content: space-between;
  line-height: 1.5;
  cursor: pointer;
  user-select: none;
  white-space: nowrap;
  min-height: 36px;
  padding: 8px 12px;
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: 14px;
  position: relative;
  border-radius: 0px;

  && {
    border: none;
    outline: none;
    box-shadow: none;
  }

  &&:focus,
  &&:focus-visible {
    border: none;
    outline: none;
    box-shadow: none;
  }

  &&[data-highlighted] {
    border-radius: 0;
    background-color: rgb(var(--text));
    color: rgb(var(--bg));
    border: none;
    outline: none;
    box-shadow: none;
  }

  &[data-disabled] {
    color: ${theme.vars.palette.grey['800']};
    font-style: italic;
  }

  &&[data-state='checked'] {
    font-weight: 700;
    border: none;
    outline: none;
    box-shadow: none;

    &::after {
      content: '✓';
      font-weight: 900;
      font-size: 14px;
      color: rgb(var(--text));
      margin-left: auto;
      padding-left: 12px;
    }
  }
`;

const SortSelectValueStyled = styled(SortSelect.SelectValue)`
  color: ${theme.vars.palette.primary.main};
`;

const SortSelectIconStyled = styled(SortSelect.Icon)``;

const SortSelectOptionTextStyled = styled(SortSelect.OptionText)``;

export const SortSelectStyled = {
  Trigger: SortSelectTriggerStyled,
  Content: SortSelectContentStyled,
  Viewport: SortSelectViewportStyled,
  Option: SortSelectOptionStyled,
  SelectValue: SortSelectValueStyled,
  OptionText: SortSelectOptionTextStyled,
  Icon: SortSelectIconStyled,
};
