---
ID: "c8bf7cad-1694-4964-8a88-3a6a2b0a0281"
Parent: "5b2d57ce-4d5f-4061-b640-9c435c9118e2"
Template: "5b2d57ce-4d5f-4061-b640-9c435c9118e2"
Path: /sitecore/templates/Feature/Common/Events/EventBody/EventBody Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {1603BC26-9207-435F-AA53-B5A43ABD6CF5}
    {DD8A1FC7-C80F-4BA1-9BC8-D1CC9376EA37}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "e5919af7-026c-45db-a651-7215dbf01122"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241023T181724Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcc9dbea-ea6f-4b26-8d4e-0f8f4eecb303"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124930Z
