---
ID: "ab7b6807-9958-44bb-9759-a359f4e65f34"
Parent: "1b53abbf-3b69-4bff-938e-a6ee7757bb0f"
Template: "1b53abbf-3b69-4bff-938e-a6ee7757bb0f"
Path: /sitecore/templates/Feature/Common/Search/NewsListingWithFilters/NewsListingWithFilters Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F23D863E-381F-405D-8228-99A5FC48C843}
    {1B53ABBF-3B69-4BFF-938E-A6EE7757BB0F}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "36c55f80-6422-4fd4-b642-a3bb4c68fcd0"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241023T181724Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f1c35e33-8e14-440a-acd0-32f9bf10d131"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jflheureux@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251023T185726Z
