---
ID: "4f353370-a662-43b3-8aff-9e01eb65f714"
Parent: "5e098290-c20c-439f-bbee-fd7d9f159c24"
Template: "5e098290-c20c-439f-bbee-fd7d9f159c24"
Path: /sitecore/templates/Feature/Common/Page Content/SimplePageListing/SimplePageListing/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "b182c0dc-848f-4318-b9aa-ac446e74e41d"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T212741Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b36a04aa-b5a0-4316-94c7-10cf6e321718"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Simple Page Listing
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124936Z
