---
ID: "17976ae7-34a8-4123-8a2f-3bbf6352cfe1"
Parent: "b249fd64-c209-4dc8-bce7-534c181a433f"
Template: "300f3d1b-52ef-4734-8eab-ae2e2a422759"
Path: /sitecore/content/Sites/main/Home/Services and Solutions/Services
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{512D851F-4224-442C-90F9-A7B850810821}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "a9506e9d-68ee-41ee-a3de-aec108238978"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{1E6CD16F-191C-452C-A649-0AB5D6375DF8}"
          p:before="*"
          s:ds="local:/Data/Card 1"
          s:id="{022420B6-3DB0-4EAB-9EA5-1F57E0F345BF}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7BC2CF07D9-FCEC-459A-A820-69469F79DA65%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
          s:ph="/headless-main/cardgrid-2" />
        <r
          uid="{8435551C-6685-4C61-9246-ACE354E1F66C}"
          p:after="r[@uid='{1E6CD16F-191C-452C-A649-0AB5D6375DF8}']"
          s:ds="local:/Data/Card 2"
          s:id="{022420B6-3DB0-4EAB-9EA5-1F57E0F345BF}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7BC2CF07D9-FCEC-459A-A820-69469F79DA65%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
          s:ph="/headless-main/cardgrid-2" />
        <r
          uid="{08D6AE25-9BCB-466B-91BD-978F122003A1}"
          p:after="r[@uid='{8435551C-6685-4C61-9246-ACE354E1F66C}']"
          s:ds="local:/Data/Card 3"
          s:id="{022420B6-3DB0-4EAB-9EA5-1F57E0F345BF}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7BC2CF07D9-FCEC-459A-A820-69469F79DA65%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=5"
          s:ph="/headless-main/cardgrid-2" />
        <r
          uid="{1826E860-798A-48AA-8D6C-85639378A0BC}"
          p:after="r[@uid='{08D6AE25-9BCB-466B-91BD-978F122003A1}']"
          s:ds="local:/Data/CommonRichtext 1"
          s:id="{45D05C34-9EDF-48D5-9226-FF2C7BC3ABB4}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles=%7C%7B1CDBD732-EAD4-4B18-9654-E8506170C542%7D%7C%7BEC0CD525-02B9-4253-A46A-71F9038434D3%7D%7C%7B789E5108-F684-4DFB-A5A7-0D1BD9BAE693%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=7"
          s:ph="/headless-main/fullwidth-6" />
        <r
          uid="{0A68337B-23C5-45BC-9F2A-0AFF039C3398}"
          p:after="r[@uid='{1826E860-798A-48AA-8D6C-85639378A0BC}']"
          s:ds="local:/Data/HeroBanner 1"
          s:id="{5E9D7B60-F61B-407B-B04B-2EEBA60B0EC0}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7B23986C32-060E-4E72-B55F-89ACF00D7B71%7D&amp;Styles=%7C%7B1CDBD732-EAD4-4B18-9654-E8506170C542%7D%7C%7B1EF4481B-B875-4A5A-8CAB-FB3BABC68428%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
          s:ph="headless-main" />
        <r
          uid="{7FBD3877-B976-43D5-9C4C-B44BFE0B425F}"
          p:after="r[@uid='{0A68337B-23C5-45BC-9F2A-0AFF039C3398}']"
          s:ds="local:/Data/CardGrid 1"
          s:id="{E78B588A-A213-411D-BFAE-DD607FFD2C8B}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames=%7BABC9BB79-78D5-4294-8398-DACD0752D20D%7D&amp;Styles=%7C%7BEC0CD525-02B9-4253-A46A-71F9038434D3%7D%7C%7B789E5108-F684-4DFB-A5A7-0D1BD9BAE693%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
          s:ph="headless-main" />
        <r
          uid="{99903E4C-61B5-44A7-A6C1-026F9A6A622F}"
          p:after="r[@uid='{7FBD3877-B976-43D5-9C4C-B44BFE0B425F}']"
          s:ds="local:/Data/FullWidth 1"
          s:id="{3C809C09-2839-4FEC-840C-43BF6F68ACC3}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=6"
          s:ph="headless-main" />
        <r
          uid="{9EE66A27-E14C-4D41-BA50-B9AE92DF9075}"
          p:after="*[1=2]"
          s:ds="local:/Data/CTABlock 1"
          s:id="{E276274F-5C13-4B76-AC83-D7A867975696}"
          s:par="GridParameters=%7BF61E01E9-711A-4C99-AE30-4E28463E1DF7%7D&amp;FieldNames&amp;Styles=%7C%7B789E5108-F684-4DFB-A5A7-0D1BD9BAE693%7D%7C%7BEC0CD525-02B9-4253-A46A-71F9038434D3%7D%7C%7BB5BE3145-F380-455F-B064-9D75F8DD01B3%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=8"
          s:ph="headless-main" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "30e85e5d-e00a-4864-b358-7624d511deb4"
    Hint: __Unversioned revision
    Value: "d04a7d11-4626-4b25-9a94-1e044584cede"
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "06fe7e7f-2451-47c0-b0cf-dc6bfeca6744"
      Hint: image
      Value: |
        <image mediaid="{C75C91BB-4B0E-4E81-B3A7-9C7B35CE385F}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251009T183939Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{FCA998C5-0CC3-4F91-94D8-0A4E6CAECE88}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: New page
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\aborsi@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\aborsi@getfishtank.ca
    - ID: "7f289a5a-f12e-46b4-aa8d-7ab26f6f8571"
      Hint: lastUpdated
      Value: 20251009T000000Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "968035c8-4fdb-4f4f-88ca-604e8fe16b62"
    - ID: "b7679bcb-b43f-4b45-a6d7-e317757cfbc0"
      Hint: datePublished
      Value: 20251009T000000Z
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\aborsi@getfishtank.ca
    - ID: "c23b27d3-398e-4a60-994a-b2257fb29b63"
      Hint: heading
      Value: Services
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251128T220140Z
