// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import {
  AccordionFacets,
  FacetItem,
  RangeFacet,
  SearchResultsAccordionFacets,
  SearchResultsFacetValueRange,
  theme,
} from '@sitecore-search/ui';

const AccordionItemCheckboxStyled = styled(AccordionFacets.ItemCheckbox)`
  background-color: white;
  width: 20px;
  height: 20px;
  display: flex;
  align-items: center;
  flex: none;
  justify-content: center;
  border: 1px solid #ccc;
  border-radius: 0px;
  cursor: pointer;
  &[data-state='checked'] {
    color: ${theme.vars.palette.primary.contrastText};
    background-color: ${theme.vars.palette.primary.main};
  }

  &:focus {
    border: solid 1px #ccc;
  }
`;

const AccordionItemToggleStyled = styled(AccordionFacets.ItemToggle)`
  width: 40px;
  height: 35px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: ${theme.vars.typography.fontSize1.fontSize};
  margin-right: ${theme.vars.spacing.s};

  &:focus {
    border: solid 1px ${theme.vars.palette.primary.main};
  }

  &[data-state='on'] {
    background-color: ${theme.vars.palette.primary.main};
    color: ${theme.vars.palette.primary.contrastText};
  }
`;

const AccordionItemCheckboxIndicatorStyled = styled(AccordionFacets.ItemCheckboxIndicator)`
  color: ${theme.vars.palette.primary.contrastText};
  width: 15px;
  height: 15px;
`;

const AccordionValueListStyled = styled(AccordionFacets.ValueList)`
  list-style: none;
  padding: 12px 0;
  margin: 0;
  max-height: 250px;
  overflow-y: auto;

  li {
    padding: 8px 16px;
    font-family: ${theme.vars.typography.fontFamilySystem};
    font-size: ${theme.vars.typography.fontSize};
    transition: background-color 0.15s ease;

    &:hover {
      background-color: #f9fafb;
    }
  }

  &[data-orientation='horizontal'] {
    display: flex;
    flex-direction: row;
    max-height: none;
    overflow: visible;
  }

  /* Custom scrollbar styling */
  &::-webkit-scrollbar {
    width: 6px;
  }

  &::-webkit-scrollbar-track {
    background: #f1f1f1;
    border-radius: 0px;
  }

  &::-webkit-scrollbar-thumb {
    background: #c1c1c1;
    border-radius: 0px;
  }

  &::-webkit-scrollbar-thumb:hover {
    background: #a8a8a8;
  }
`;

const AccordionItemCheckboxLabelStyled = styled(AccordionFacets.ItemLabel)`
  padding-left: 12px;
  font-size: 14px;
  color: #374151;
  cursor: pointer;
  flex: 1;
`;

const AccordionItemStyled = styled(FacetItem)`
  display: flex;
  align-items: center;
  padding: 4px 0;
  cursor: pointer;

  &:hover {
    background-color: transparent;
  }
`;

const AccordionHeaderStyled = styled(AccordionFacets.Header)`
  display: flex;
  margin: 0;
`;

const AccordionTriggerStyled = styled(AccordionFacets.Trigger)`
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  min-width: 200px;
  padding: 12px 16px;
  background-color: white;
  border: 1px solid #d1d5db;
  border-radius: 0px;
  color: ${theme.vars.palette.text.primary};
  font-size: ${theme.vars.typography.fontSize};
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  position: relative;

  &:hover {
    border-color: ${theme.vars.palette.primary.main};
    box-shadow: 0 0 0 1px ${theme.vars.palette.primary.main}20;
  }

  &:focus {
    outline: none;
    border-color: ${theme.vars.palette.primary.main};
    box-shadow: 0 0 0 2px ${theme.vars.palette.primary.main}20;
  }

  &[data-state='open'] {
    border-color: ${theme.vars.palette.primary.main};
    border-bottom-left-radius: 0px;
    border-bottom-right-radius: 0px;
    box-shadow: 0 0 0 1px ${theme.vars.palette.primary.main}20;
  }

  /* Dropdown arrow */
  &::after {
    content: '';
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 4px solid #6b7280;
    transition: transform 0.2s ease;
    margin-left: 8px;
  }

  &[data-state='open']::after {
    transform: rotate(180deg);
  }
`;

const AccordionFacetsFacetStyled = styled(AccordionFacets.Facet)`
  position: relative;
  margin: 0;
  flex-shrink: 0;
  min-width: 200px;
  width: auto;
`;

const AccordionFacetsContentStyled = styled(AccordionFacets.Content)`
  position: absolute;
  top: 100%;
  left: 0;
  width: max-content;
  min-width: 100%;
  max-width: 300px;
  z-index: 50;
  background-color: white;
  border: 1px solid #d1d5db;
  border-top: none;
  border-bottom-left-radius: 0px;
  border-bottom-right-radius: 0px;
  box-shadow:
    0 10px 15px -3px rgba(0, 0, 0, 0.1),
    0 4px 6px -2px rgba(0, 0, 0, 0.05);

  &[data-state='open'] {
    animation: slideDown 0.2s ease-out;
  }

  &[data-state='closed'] {
    animation: slideUp 0.15s ease-in;
  }

  @keyframes slideDown {
    from {
      opacity: 0;
      transform: translateY(-4px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }

  @keyframes slideUp {
    from {
      opacity: 1;
      transform: translateY(0);
    }
    to {
      opacity: 0;
      transform: translateY(-4px);
    }
  }
`;

const AccordionFacetsRootStyled = styled(SearchResultsAccordionFacets)`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 24px;
  align-items: flex-start;
  margin-bottom: 12px;
`;

export const DropdownFacetsStyled = {
  Trigger: AccordionTriggerStyled,
  Header: AccordionHeaderStyled,
  Item: AccordionItemStyled,
  ItemCheckboxLabel: AccordionItemCheckboxLabelStyled,
  ValueList: AccordionValueListStyled,
  ItemCheckboxIndicator: AccordionItemCheckboxIndicatorStyled,
  ItemToggle: AccordionItemToggleStyled,
  ItemCheckbox: AccordionItemCheckboxStyled,
  Facet: AccordionFacetsFacetStyled,
  Root: AccordionFacetsRootStyled,
  Content: AccordionFacetsContentStyled,
};

const RangeFacetRootStyled = styled(SearchResultsFacetValueRange)`
  position: relative;
  display: flex;
  align-items: center;
  user-select: none;
  touch-action: none;
  width: 100%;
  height: 20px;
  margin-bottom: ${theme.vars.spacing.l};
`;

const RangeFacetTrackStyled = styled(RangeFacet.Track)`
  background-color: ${theme.vars.palette.grey['400']};
  position: relative;
  flex-grow: 1;
  border-radius: 0px;
  height: 3px;
`;

const RangeFacetRangeStyled = styled(RangeFacet.Range)`
  position: absolute;
  background-color: ${theme.vars.palette.primary.main};
  border-radius: 0px;
  height: 100%;
`;

const indicatorStyles = `
  display: block;
  width: 20px;
  height: 20px;
  background-color: white;
  box-shadow: 0 2px 10px grey;
  border-radius: 0px;
  font-family: ${theme.vars.typography.fontFamilySystem};
  font-size: 10px;
  line-height: 20px;
  text-align: center;
  cursor: pointer;

  &:hover {
    background-color: ${theme.vars.palette.primary.main};
  }

  &:focus {
    outline: none;
    box-shadow: 0 0 0 3px grey;
  }

  span {
    position: absolute;
    left: 0;
    top: 30px;
    font-size: 14px;
    font-family: ${theme.vars.typography.fontFamilySystem};
  }

  `;

const RangeFacetStartStyled = styled(RangeFacet.Start)`
  ${indicatorStyles}
`;
const RangeFacetEndStyled = styled(RangeFacet.End)`
  ${indicatorStyles}
`;

export const RangeFacetStyled = {
  Root: RangeFacetRootStyled,
  Track: RangeFacetTrackStyled,
  Range: RangeFacetRangeStyled,
  Start: RangeFacetStartStyled,
  End: RangeFacetEndStyled,
};
