---
ID: "516bcbc9-6f41-4518-8e00-9ec791eece56"
Parent: "82c3ea9c-4e75-42d0-9ae3-131fe6951d3b"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/content/Sites/main/Presentation/Page Branches/Product Page
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20251125T200310Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\daustin@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\daustin@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bc6bd68b-8b0a-47aa-a488-acfd0fb18785"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\daustin@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251125T200310Z
