---
ID: "f270311a-be37-4dd4-975d-1fa19e7095ba"
Parent: "25806bed-4f51-4095-bb58-dfcefb6bea5d"
Template: "25806bed-4f51-4095-bb58-dfcefb6bea5d"
Path: /sitecore/templates/Feature/Common/Search/SimplePageListingWithFilters/SimplePageListingWithFilters Parameters/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "23758bf4-152a-4db4-9f81-947655b72f47"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e60caa8e-c6aa-4c11-b59f-665d8d3b4838"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\kparks@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250812T210948Z
