---
ID: "4ee69d43-c7a9-498b-9733-92c06be47470"
Parent: "effa7fa6-82c8-487a-9be9-e0c5da45f1cd"
Template: "effa7fa6-82c8-487a-9be9-e0c5da45f1cd"
Path: /sitecore/templates/Foundation/Common/Location/Location Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {54971594-C0AB-4BFB-BD0B-EF6506E5A7C3}
    {EFFA7FA6-82C8-487A-9BE9-E0C5DA45F1CD}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241216T202017Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1225abff-a404-4daf-8d36-09ddb5807ca0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\jflores@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241216T202036Z
