# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: headapps/nextjs-starter
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        cache: 'npm'
        cache-dependency-path: headapps/nextjs-starter/package-lock.json
    - name: Install dependencies
      run: npm ci
    - name: Run Chromatic
      uses: chromaui/action@latest
      with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        skip: "dependabot/**"
        workingDir: headapps/nextjs-starter
