// This component was generated by @sitecore-search/cli on Thu Aug 07 2025 12:38:39 GMT-0400 (Eastern Daylight Saving Time)

import { styled } from 'styled-components';

import { theme } from '@sitecore-search/ui';

const FilterContainer = styled.div`
  margin-bottom: ${theme.vars.spacing.m};
`;

const FilterHeaderContainer = styled.div`
  display: flex;
  margin-bottom: ${theme.vars.spacing.s};
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
`;

const FilterHeader = styled.div`
  margin: 0;
`;

const SelectedFiltersList = styled.div`
  display: flex;
  flex-wrap: wrap;
  padding: 12px 0;
`;

const ClearFilters = styled.button`
  background: none;
  border: none;
  text-decoration: underline;
  font-size: ${theme.vars.typography.fontSize};
  &:hover {
    color: ${theme.vars.palette.primary.main};
    cursor: pointer;
  }
`;

export const FiltersStyled = {
  Container: FilterContainer,
  HeaderContainer: FilterHeaderContainer,
  Header: FilterHeader,
  ClearFilters,
  SelectedFiltersList,
};
