---
ID: "ee6b4fce-b825-495c-8585-5c62522e3d53"
Parent: "44c67c52-d346-4da3-a1fd-ffbfd127dd13"
Template: "44c67c52-d346-4da3-a1fd-ffbfd127dd13"
Path: /sitecore/templates/Feature/Common/Page Content/Video/Video/__Standard Values
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "5d6fbc4e-bb3b-4f4f-9102-ed2311a0c0da"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "06fe7e7f-2451-47c0-b0cf-dc6bfeca6744"
      Hint: image
      Value: |
        <image mediaid="{FB70BF8B-1254-4326-8FB7-C136E49E68C8}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250609T202658Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\athomas@getfishtank.ca
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9b4f1566-4118-4f43-9ab9-7cb8131b236b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rbarbedo@getfishtank.ca
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250616T124936Z
